// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(HamburguerContext))]
    partial class HamburguerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Backend.Entities.Models.Hamburguer", b =>
                {
                    b.Property<int>("HamburguerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HamburguerId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Hamburguers");
                });

            modelBuilder.Entity("Backend.Entities.Models.HamburguersIngredient", b =>
                {
                    b.Property<int>("HamburguersIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamburguerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HamburguersIngredientId");

                    b.HasIndex("HamburguerId");

                    b.HasIndex("IngredientId");

                    b.ToTable("HamburguersIngredients");
                });

            modelBuilder.Entity("Backend.Entities.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mesure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Backend.Entities.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Backend.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Entities.Models.UsersHamburguer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HamburguerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersHamburguerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "HamburguerId");

                    b.HasIndex("HamburguerId");

                    b.ToTable("UsersHamburguers");
                });

            modelBuilder.Entity("Backend.Entities.Models.Hamburguer", b =>
                {
                    b.HasOne("Backend.Entities.Models.Restaurant", "Restaurant")
                        .WithMany("Hamburguers")
                        .HasForeignKey("RestaurantId")
                        .HasConstraintName("FK_Hamburguers_Restaurants_RestaurantId")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.Models.HamburguersIngredient", b =>
                {
                    b.HasOne("Backend.Entities.Models.Hamburguer", "Hamburguer")
                        .WithMany("HamburguersIngredients")
                        .HasForeignKey("HamburguerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Models.Ingredient", "Ingredient")
                        .WithMany("HamburguersIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Entities.Models.UsersHamburguer", b =>
                {
                    b.HasOne("Backend.Entities.Models.Hamburguer", "Hamburguer")
                        .WithMany("UsersHamburguers")
                        .HasForeignKey("HamburguerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Models.User", "User")
                        .WithMany("UsersHamburguers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
